# Requête 2 :
# Les équipements publics culturels qui ouvrent le jeudi
# et qui sont proches d'un parking possédant au moins 5 places
# encore disponibles et qui accepte le système de paiement Moneo

prefix sc: <http://schema.org/>
prefix ex2: <http://www.example.org/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dcterms:  <http://purl.org/dc/terms/>
prefix dbpedia:  <http://dbpedia.org/resource/>
prefix ical: <http://www.w3.org/2002/12/cal/icaltzd#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>"

prefix schema:  <http://example.org/>
prefix parking:  <http://example.org/Parking/>
prefix geo:     <http://example.org/GeoCoordinates/>
prefix postalAddress:  <http://example.org/PostalAddress/>

SELECT distinct ?nomEquipement ?adrEquipement
    ?nomParking ?adrParking
    (xsd:integer(?dispo) - xsd:integer(?complet) as ?placesDispo)
WHERE {
     ?equip dcterms:subject dbpedia:Culture ;
            sc:name ?nomEquipement ;
            ical:Vcalendar ?cal ;
            sc:address ?addrE ;
            ex:parkingClose ?parking .

     ?addrE sc:streetAddress ?adrEquipement .

     ?cal ical:Vevent ?event .
     ?event ical:rrule ?rule .
     ?rule ical:byday ?days
     FILTER(contains(?days, "TH"))

     ?parking parking:name ?nomParking ;
              parking:address ?addrP ;
              parking:paymentAccepted ?payment ;
              ex2:dispo ?dispo ;
              ex2:complet ?complet
     FILTER regex(?payment, "MONEO")
     FILTER(xsd:integer(?dispo) - xsd:integer(?complet) > 5)

     ?addrP sc:streetAddress ?adrParking .
}
ORDER BY ?nomEquip