# Sélectionner toutes les activités, restaurants et caves accessibles au handicapé visuel, auditif et ayant une adresse mail ainsi qu'un site web
# Retourne le Nom , adresse, code postal et commune + le type (resto, cave, activité)


SELECT ?type ?name ?address ?postalCode ?town ?webSite ?mail
WHERE 
{
				
	?lieu	rdf:type ?type;
			onto:hasName ?name;
			onto:hasAddress ?address;
			onto:hasPostalCode ?postalCode;
			onto:hasTown ?town;
			onto:hasWebSite ?webSite;
			onto:hasMail ?mail;
			onto:acceptVisualImpairment "Oui";
			onto:acceptHearingImpairment "Oui".
}

# Est-ce qu'on a le droit d'ajouter une information Type ? --> Si non on l'affiche pas
# Si on veut par exemple définir une propriété spécifique à un dataSet Comment ça se passe pour la requête (Elle retournera un truc vide ?)
# ex: nb étoile pour le restaurant

Class:

LocationActivity
Restaurant
Cave

Ontologie Globale:

onto:hasName
onto:hasAddress
onto:hasPostalCode
onto:hasTown
onto:hasWebSite
onto:hasMail
onto:acceptVisualImpairment
onto:acceptHearingImpairment

V1Restaurant(x, ad, pc, town):- Address(x, ad) ^ PostalCode(x, pc) ^ Town(x, town)
SELECT ?x ?ad ?pc ?town
WHERE
{
	?x	onto:hasAdrress ?ad;
		onto:hasPostalCode ?pc;
		onto;hasTown ?town.	
}

V2Restaurant(x, mail, wb):- Mail(x, mail) ^ WebSite(x, wb)
V3Restaurant(x, vi, hi):- VisualImpairment(x, vi) ^ HearingImpairment(x, hi)